"""add new billing report

Revision ID: 07cdfd6fca19
Revises: c2ff0263cc2b
Create Date: 2024-01-23 10:57:05.930649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cdfd6fca19'
down_revision = 'c2ff0263cc2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pubsub_report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Numeric(precision=65, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pubsub_report'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pubsub_report')
    # ### end Alembic commands ###
