"""modify billing table

Revision ID: 9ca6b9af842e
Revises: 07cdfd6fca19
Create Date: 2024-02-25 12:18:38.888998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ca6b9af842e'
down_revision = '07cdfd6fca19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_report', sa.Column('total_cost', sa.Numeric(precision=65, scale=2), nullable=False))
    op.add_column('billing_report', sa.Column('discounted_cost', sa.Numeric(precision=65, scale=2), nullable=False))
    op.add_column('billing_report', sa.Column('tech_fee', sa.Numeric(precision=65, scale=2), nullable=False))
    op.drop_column('billing_report', 'dealing_fee')
    op.drop_column('billing_report', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_report', sa.Column('cost', mysql.DECIMAL(precision=65, scale=2), nullable=False))
    op.add_column('billing_report', sa.Column('dealing_fee', mysql.DECIMAL(precision=65, scale=2), nullable=False))
    op.drop_column('billing_report', 'tech_fee')
    op.drop_column('billing_report', 'discounted_cost')
    op.drop_column('billing_report', 'total_cost')
    # ### end Alembic commands ###
