"""add billing report

Revision ID: c2ff0263cc2b
Revises: 
Create Date: 2023-06-17 10:56:21.250333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ff0263cc2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Numeric(precision=65, scale=2), nullable=False),
    sa.Column('dealing_fee', sa.Numeric(precision=65, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_report'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_report')
    # ### end Alembic commands ###
